---
title: A MULTIVARIATE EQUIVALENCY AND GENERAL TEST FOR RENSCH'S RULE: IMPLICATIONS FOR THE EVOLUTION OF SEXUAL SHAPE DIMORPHISM

output:
  pdf_document:
    fig_caption: yes
    number_sections: no  #note: change to 'no' for most journals
    keep_tex: false
    pandoc_args:

    
csl: evolution.csl
bibliography: bibliography.bib

header-includes:
  - \usepackage{setspace}\doublespacing
  - \usepackage{lineno}\linenumbers

---
\begin{center}
\textbf{Dean C. Adams$^{1,*}$, Elizabeth Glynne$^{1}$ and Antigoni Kaliontzopoulou$^2$}
\end{center}

\begin{center}`r format(Sys.time(), '%d %B, %Y')`\end{center}

$^{1}$Department of Ecology, Evolution, and Organismal Biology, Iowa State University, Ames, Iowa, USA.

$^{2}$CIBIO Research Centre in Biodiversity and Genetic Resources, InBIO, Universidade do Porto, Campus de Vairão. Vila do Conde, Portugal. 

$^{*}$Correspondence: Dean C. Adams <dcadams@iastate.edu> 

\hfill\break
**Keywords**: Sexual dimorphism, multivariate, morphological evolution \hfill\break

**Short Title**: Multivariate Test of Rensch's Rule \hfill\break

**Author Contributions**: DCA devised the approach, AK provided the empirical example; all authors contributed  to all parts of this manuscript. \hfill\break

**Data Archiving**: Data will be made available on DRYAD upon publication. \hfill\break

**Acknowledgments**: We thank XXX for comments on drafts of this manuscript; Ana Perera, Inés Freitas and Daniele Salvi for the phylogeny reconstruction; and Chiara Ripa and Zélia Pereira for aiding shape data acquisition. This work was  sponsored in part by National Science Foundation Grant DBI-1902511 (to DCA), and by FEDER Funds through the Operational Competitiveness Factors Program - COMPETE and National Funds through FCT - Foundation for Science and Technology within the scope of the project “PTDC/BIA-EVL/28090/2017 - POCI-01-0145-FEDER-028090” (to AK).



