---
title: A Standardized Effect Size for Evaluating the Strength of Phylogenetic Signal, and Why Lambda is not Appropriate

output:
  pdf_document:
    fig_caption: yes
    number_sections: no  #note: change to 'no' for most journals
    keep_tex: false
    pandoc_args:

    
csl: evolution.csl
bibliography: bibliography.bib

header-includes:
  - \usepackage{setspace}\doublespacing
  - \usepackage{lineno}\linenumbers

---
\begin{center}
\textbf{Dean C. Adams$^{1,*}$, Michael L. Collyer$^2$ and Erica K. Baken$^{1}$}
\end{center}

\begin{center}`r format(Sys.time(), '%d %B, %Y')`\end{center}

$^{1}$Department of Ecology, Evolution, and Organismal Biology, Iowa State University, Ames, Iowa, USA.

$^{2}$Department of Science, Chatham University, Pittsburgh, Pennsylvania, USA. 

$^{*}$Correspondence: Dean C. Adams <dcadams@iastate.edu> 

\hfill\break

**Keywords**: phylogenetic signal, effect size, Pagel's lambda \hfill\break

**Short Title**: An Effect Size for Phylogenetic Signal \hfill\break

**Author Contributions**: DCA ...EKB...; all authors contributed  to all parts of this manuscript. \hfill\break

**Data Archiving**: Data will be made available on DRYAD upon publication. \hfill\break

**Acknowledgments**: We thank XXX for comments on drafts of this manuscript; ...... This work was  sponsored in part by National Science Foundation Grant DBI-1902511 (to DCA) and DBI-1902694 (to MLC).



